# Use Alpine Linux as the base image
FROM openjdk:8-jre-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file generated by Maven into the container
COPY target/Foyer-0.0.1-SNAPSHOT.jar /app/Foyer.jar

# Expose the port that your application listens on
EXPOSE 8181

# Define the command to run your application
CMD ["java", "-jar", "Foyer.jar"]

