version: "3.8"

services:
  foyer-api:
    build: .
    restart: always
    ports:
      - 8809:8181
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3301:3331
    environment:
      MYSQL_DATABASE: Foyer
      MYSQL_ALLOW_EMPTY_PASSWORD: ""

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/vagrant/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
